// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTTmSRInFfP_SimxLxGH0jGiErI7jcjPA',
    appId: '1:1024877750483:web:81c47aff40d8d27ea70c26',
    messagingSenderId: '1024877750483',
    projectId: 'melody-2b36b',
    authDomain: 'melody-2b36b.firebaseapp.com',
    storageBucket: 'melody-2b36b.appspot.com',
    measurementId: 'G-XCWK9YTVHB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpW3OwVa_lfyHxBz-UK0xANCA67qAg_DA',
    appId: '1:1024877750483:android:d559624ac3f6225aa70c26',
    messagingSenderId: '1024877750483',
    projectId: 'melody-2b36b',
    storageBucket: 'melody-2b36b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAc21YbIN3ySohd6jBLEkvQ6IVqZNqcbK8',
    appId: '1:1024877750483:ios:f1242fe4fa823ddfa70c26',
    messagingSenderId: '1024877750483',
    projectId: 'melody-2b36b',
    storageBucket: 'melody-2b36b.appspot.com',
    iosBundleId: 'com.anandnet.harmonymusic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAc21YbIN3ySohd6jBLEkvQ6IVqZNqcbK8',
    appId: '1:1024877750483:ios:a50444835490fcffa70c26',
    messagingSenderId: '1024877750483',
    projectId: 'melody-2b36b',
    storageBucket: 'melody-2b36b.appspot.com',
    iosBundleId: 'com.example.harmonymusic',
  );
}
